from pathlib import Path

library_path = Path('Library.lua')
theme_path = Path('addons/ThemeManager.lua')
library = library_path.read_text()
theme = theme_path.read_text()


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 match, got {count}')
    return text.replace(old, new, 1)

# Overlay alignment.
theme = replace_once(theme, "\t\t\tVisibleAnchor = Vector2.new(0.08, 0.855);", "\t\t\tVisibleAnchor = Vector2.new(0.08, 0.832);", 'Marin gap alignment')

# Restore boxed keybind badges and remove angle brackets.
library = replace_once(library, """        local PickOuter = Library:Create('Frame', {\n            BackgroundTransparency = 1;\n            BorderSizePixel = 0;\n            Size = UDim2.new(0, 28, 0, 15);\n            ZIndex = 6;\n            Parent = ToggleLabel;\n        });\n\n        local PickInner = Library:Create('Frame', {\n            BackgroundTransparency = 1;\n            BorderSizePixel = 0;\n            Size = UDim2.new(1, 0, 1, 0);\n            ZIndex = 7;\n            Parent = PickOuter;\n        });\n\n        Library:AddToRegistry(PickInner, {\n            BackgroundColor3 = 'BackgroundColor';\n            BorderColor3 = 'OutlineColor';\n        });""", """        local PickOuter = Library:Create('Frame', {\n            BackgroundColor3 = Color3.new(0, 0, 0);\n            BorderColor3 = Color3.new(0, 0, 0);\n            Size = UDim2.new(0, 28, 0, 15);\n            ZIndex = 6;\n            Parent = ToggleLabel;\n        });\n\n        local PickInner = Library:Create('Frame', {\n            BackgroundColor3 = Library.BackgroundColor;\n            BorderColor3 = Library.OutlineColor;\n            BorderMode = Enum.BorderMode.Inset;\n            Size = UDim2.new(1, 0, 1, 0);\n            ZIndex = 7;\n            Parent = PickOuter;\n        });\n\n        Library:AddCorner(PickOuter, 3);\n        Library:AddCorner(PickInner, 3);\n        Library:AddToRegistry(PickOuter, { BorderColor3 = 'Black'; });\n        Library:AddToRegistry(PickInner, {\n            BackgroundColor3 = 'BackgroundColor';\n            BorderColor3 = 'OutlineColor';\n        });""", 'keybind boxed surfaces')
library = replace_once(library, "            Text = '<' .. Info.Default .. '>';", "            Text = tostring(Info.Default);", 'keybind initial text')
library = replace_once(library, "            DisplayLabel.Text = '<' .. tostring(Key) .. '>';", "            DisplayLabel.Text = tostring(Key);", 'keybind set text')
library = replace_once(library, "                DisplayLabel.Text = '<...>';", "                DisplayLabel.Text = '...';", 'keybind capture text')
library = replace_once(library, "            PickOuter.Size = UDim2.fromOffset(math.max(28, Width + 6), 15);", "            PickOuter.Size = UDim2.fromOffset(math.max(28, Width + 10), 15);", 'keybind padding')

# Remove keybind menu accent strip, preserve accent border/glow.
color_frame_block = """    local ColorFrame = Library:Create('Frame', {\n        BackgroundColor3 = Library.AccentColor;\n        BorderSizePixel = 0;\n        Size = UDim2.new(1, 0, 0, 2);\n        ZIndex = 102;\n        Parent = KeybindInner;\n    });\n\n    Library:AddToRegistry(ColorFrame, {\n        BackgroundColor3 = 'AccentColor';\n    }, true);\n\n"""
library = replace_once(library, color_frame_block, '', 'keybind accent strip')

# Single active tooltip.
library = replace_once(library, "    local FollowConnection\n    local ActiveTweens = {}\n\n    local function CancelTweens()", "    local FollowConnection\n    local ActiveTweens = {}\n    local Hide\n\n    local function CancelTweens()", 'tooltip forward declaration')
library = replace_once(library, "    local function Show()\n        AnimationId = AnimationId + 1\n        local CurrentId = AnimationId\n\n        CancelTweens()", "    local function Show()\n        if Library.ActiveTooltipHide and Library.ActiveTooltipHide ~= Hide then\n            Library.ActiveTooltipHide(true)\n        end\n        Library.ActiveTooltipHide = Hide\n\n        AnimationId = AnimationId + 1\n        local CurrentId = AnimationId\n\n        CancelTweens()", 'tooltip show arbitration')
library = replace_once(library, "    local function Hide()\n        if not Tooltip.Visible then\n            return\n        end\n\n        AnimationId = AnimationId + 1", "    Hide = function(Instant)\n        if not Tooltip.Visible then\n            if Library.ActiveTooltipHide == Hide then\n                Library.ActiveTooltipHide = nil\n            end\n            return\n        end\n\n        if Instant then\n            AnimationId = AnimationId + 1\n            CancelTweens()\n            IsHovering = false\n            Tooltip.Visible = false\n            if FollowConnection then\n                FollowConnection:Disconnect()\n                FollowConnection = nil\n            end\n            if Library.ActiveTooltipHide == Hide then\n                Library.ActiveTooltipHide = nil\n            end\n            return\n        end\n\n        AnimationId = AnimationId + 1", 'tooltip instant hide')
library = replace_once(library, "            Tooltip.Visible = false\n\n            if FollowConnection then", "            Tooltip.Visible = false\n            if Library.ActiveTooltipHide == Hide then\n                Library.ActiveTooltipHide = nil\n            end\n\n            if FollowConnection then", 'tooltip cleanup')

# Longer main-tab transitions.
library = replace_once(library, "                    SetTabVisualGroups(0, 0.22, 0.018);", "                    SetTabVisualGroups(0, 0.38, 0.018);", 'tab fade in')
library = replace_once(library, "                    Library:TweenProperty(TabFrame, 'Position', UDim2.new(0, 0, 0, 0), 0.26);", "                    Library:TweenProperty(TabFrame, 'Position', UDim2.new(0, 0, 0, 0), 0.42);", 'tab move in')
library = replace_once(library, "            SetTabVisualGroups(1, 0.14, 0);", "            SetTabVisualGroups(1, 0.30, 0);", 'tab fade out')
library = replace_once(library, "            Library:TweenProperty(TabFrame, 'Position', UDim2.new(0, 0, 0, -4), 0.17);", "            Library:TweenProperty(TabFrame, 'Position', UDim2.new(0, 0, 0, -5), 0.32);", 'tab move out')
library = replace_once(library, "            task.delay(0.17, function()", "            task.delay(0.32, function()", 'tab hide delay')

# Dependency state guard.
library = replace_once(library, """            local Height = Layout.AbsoluteContentSize.Y;\n            DependencyVisible = Visible;\n\n            if Visible then""", """            local Height = Layout.AbsoluteContentSize.Y;\n\n            if Visible == DependencyVisible and Holder.Visible == Visible then\n                if Visible then\n                    if Instant then\n                        Holder.Size = UDim2.new(1, 0, 0, Height);\n                    else\n                        Library:TweenProperty(Holder, 'Size', UDim2.new(1, 0, 0, Height), 0.18);\n                    end\n                    Groupbox:Resize();\n                end\n                return;\n            end\n\n            DependencyVisible = Visible;\n\n            if Visible then""", 'dependency stable state guard')

# Dropdown popup constants / references.
library = replace_once(library, """        local ListHeight = MAX_DROPDOWN_ITEMS * 20 + 2\n        local ListGap = 5\n        local ListTargetPosition = UDim2.fromOffset(0, 0)""", """        local POPUP_GAP = 5\n        local SEARCH_HEIGHT = 20\n        local VALUES_TOP = POPUP_GAP + SEARCH_HEIGHT + POPUP_GAP\n        local POPUP_BOTTOM = 5\n        local ListRowsHeight = MAX_DROPDOWN_ITEMS * 20 + 1\n        local ListHeight = VALUES_TOP + ListRowsHeight + POPUP_BOTTOM\n        local ListGap = 5\n        local ListTargetPosition = UDim2.fromOffset(0, 0)\n        local Scrolling\n        local ScrollTrack""", 'dropdown popup constants')
library = replace_once(library, """        local function RecalculateListSize(YSize)\n            local RequestedHeight = tonumber(YSize) or (MAX_DROPDOWN_ITEMS * 20 + 2);\n            ListHeight = math.clamp(RequestedHeight, 1, MAX_DROPDOWN_ITEMS * 20 + 2);\n            ListOuter.Size = UDim2.fromOffset(math.max(DropdownOuter.AbsoluteSize.X, 1), ListHeight);\n        end;""", """        local function RecalculateListSize(YSize)\n            local RequestedHeight = tonumber(YSize) or (MAX_DROPDOWN_ITEMS * 20 + 1);\n            ListRowsHeight = math.clamp(RequestedHeight, 20, MAX_DROPDOWN_ITEMS * 20 + 1);\n            ListHeight = VALUES_TOP + ListRowsHeight + POPUP_BOTTOM;\n            ListOuter.Size = UDim2.fromOffset(math.max(DropdownOuter.AbsoluteSize.X, 1), ListHeight);\n\n            if Scrolling then\n                Scrolling.Position = UDim2.fromOffset(POPUP_GAP, VALUES_TOP);\n                Scrolling.Size = UDim2.new(1, -(POPUP_GAP * 2), 0, ListRowsHeight);\n            end\n\n            if ScrollTrack then\n                ScrollTrack.Position = UDim2.new(1, -2, 0, VALUES_TOP + 4);\n                ScrollTrack.Size = UDim2.new(0, 3, 0, math.max(ListRowsHeight - 8, 1));\n            end\n        end;""", 'dropdown popup sizing')

# Search bar before list viewport.
search_ui = """        local SearchOuter = Library:Create('Frame', {\n            BackgroundColor3 = Color3.new(0, 0, 0);\n            BorderColor3 = Color3.new(0, 0, 0);\n            Position = UDim2.fromOffset(POPUP_GAP, POPUP_GAP);\n            Size = UDim2.new(1, -(POPUP_GAP * 2), 0, SEARCH_HEIGHT);\n            ZIndex = 23;\n            Parent = ListInner;\n        });\n\n        local SearchInner = Library:Create('Frame', {\n            BackgroundColor3 = Library.MainColor;\n            BorderColor3 = Library.OutlineColor;\n            BorderMode = Enum.BorderMode.Inset;\n            Size = UDim2.fromScale(1, 1);\n            ZIndex = 24;\n            Parent = SearchOuter;\n        });\n\n        Library:AddCorner(SearchOuter, 3);\n        Library:AddCorner(SearchInner, 3);\n        Library:AddToRegistry(SearchOuter, { BorderColor3 = 'Black'; });\n        Library:AddToRegistry(SearchInner, {\n            BackgroundColor3 = 'MainColor';\n            BorderColor3 = 'OutlineColor';\n        });\n\n        local SearchBox = Library:Create('TextBox', {\n            BackgroundTransparency = 1;\n            BorderSizePixel = 0;\n            ClearTextOnFocus = false;\n            PlaceholderColor3 = Color3.fromRGB(155, 155, 155);\n            PlaceholderText = 'Search...';\n            Position = UDim2.fromOffset(6, 0);\n            Size = UDim2.new(1, -12, 1, 0);\n            Text = '';\n            TextColor3 = Library.FontColor;\n            TextSize = 13;\n            TextStrokeTransparency = 0;\n            TextXAlignment = Enum.TextXAlignment.Left;\n            ZIndex = 25;\n            Parent = SearchInner;\n        });\n        Library:ApplyFont(SearchBox);\n        Library:ApplyTextStroke(SearchBox);\n        Library:AddToRegistry(SearchBox, { TextColor3 = 'FontColor'; });\n\n"""
library = replace_once(library, "        local Scrolling = Library:Create('ScrollingFrame', {\n", search_ui + "        Scrolling = Library:Create('ScrollingFrame', {\n", 'dropdown search UI')
library = replace_once(library, """            CanvasSize = UDim2.new(0, 0, 0, 0);\n            Size = UDim2.new(1, 0, 1, 0);\n            ZIndex = 21;""", """            CanvasSize = UDim2.new(0, 0, 0, 0);\n            Position = UDim2.fromOffset(POPUP_GAP, VALUES_TOP);\n            Size = UDim2.new(1, -(POPUP_GAP * 2), 0, ListRowsHeight);\n            ZIndex = 21;""", 'dropdown values viewport')
library = replace_once(library, "        local ScrollTrack = Library:Create('Frame', {", "        ScrollTrack = Library:Create('Frame', {", 'scroll track scope')
library = replace_once(library, """            Position = UDim2.new(1, -1, 0, 4);\n            Size = UDim2.new(0, 3, 1, -8);""", """            Position = UDim2.new(1, -2, 0, VALUES_TOP + 4);\n            Size = UDim2.new(0, 3, 0, math.max(ListRowsHeight - 8, 1));""", 'scroll track geometry')
library = replace_once(library, """            local TrackHeight = math.max(ScrollTrack.AbsoluteSize.Y, 1);\n            local ThumbHeight = math.clamp(TrackHeight * (ViewportHeight / ContentHeight), 18, TrackHeight);""", """            local TrackHeight = math.max(ScrollTrack.AbsoluteSize.Y, 1);\n            local MinThumbHeight = math.min(18, TrackHeight);\n            local ThumbHeight = math.clamp(TrackHeight * (ViewportHeight / ContentHeight), MinThumbHeight, TrackHeight);""", 'scroll clamp')

# Searchable rows + programmatic SetValue.
library = replace_once(library, """        function Dropdown:BuildDropdownList()\n            local Values = Dropdown.Values;\n            local Buttons = {};""", """        local Buttons = {};\n\n        function Dropdown:BuildDropdownList()\n            local Values = Dropdown.Values;\n            table.clear(Buttons);""", 'button table scope')
library = replace_once(library, """                Table:UpdateButton();\n                Dropdown:Display();\n\n                Buttons[Button] = Table;""", """                Table.Button = Button;\n                Table.Value = Value;\n                Table:UpdateButton();\n                Dropdown:Display();\n\n                Buttons[Button] = Table;""", 'row metadata')
library = replace_once(library, """            Scrolling.CanvasSize = UDim2.fromOffset(0, (Count * 20) + 8);\n\n            local Y = math.clamp(Count * 20, 0, MAX_DROPDOWN_ITEMS * 20) + 1;\n            RecalculateListSize(Y);""", """            Scrolling.CanvasSize = UDim2.fromOffset(0, (Count * 20) + 8);\n\n            local Y = math.max(20, math.clamp(Count * 20, 0, MAX_DROPDOWN_ITEMS * 20) + 1);\n            RecalculateListSize(Y);""", 'build list sizing')
library = replace_once(library, """        function Dropdown:OnChanged(Func)\n            Dropdown.Changed = Func;\n            Func(Dropdown.Value);\n        end;\n\n        function Dropdown:SetValues(NewValues)""", """        function Dropdown:OnChanged(Func)\n            Dropdown.Changed = Func;\n            Func(Dropdown.Value);\n        end;\n\n        function Dropdown:SetValue(NewValue)\n            if Info.Multi then\n                local NewSelection = {};\n                if type(NewValue) == 'table' then\n                    for Key, Value in next, NewValue do\n                        if type(Key) == 'number' then\n                            NewSelection[Value] = true;\n                        elseif Value then\n                            NewSelection[Key] = true;\n                        end\n                    end\n                end\n                Dropdown.Value = NewSelection;\n            else\n                if NewValue == nil and not Info.AllowNull then\n                    return;\n                end\n                if NewValue ~= nil and not table.find(Dropdown.Values, NewValue) then\n                    return;\n                end\n                Dropdown.Value = NewValue;\n            end\n\n            for _, Table in next, Buttons do\n                Table:UpdateButton();\n            end\n            Dropdown:Display();\n            Library:SafeCallback(Dropdown.Callback, Dropdown.Value);\n            Library:SafeCallback(Dropdown.Changed, Dropdown.Value);\n        end;\n\n        function Dropdown:SetValues(NewValues)""", 'dropdown SetValue')

# Forward-declare scroll visual updater so search callbacks can invoke it.
library = replace_once(library, "        local function UpdateDropdownScrollVisuals()\n            local ViewportHeight", "        local UpdateDropdownScrollVisuals\n        UpdateDropdownScrollVisuals = function()\n            local ViewportHeight", 'scroll updater forward declaration')

search_logic = """        local function ApplyDropdownSearch()\n            local Query = string.lower(SearchBox.Text or '');\n            local VisibleCount = 0;\n\n            for _, Table in next, Buttons do\n                local ValueText = string.lower(tostring(Table.Value or ''));\n                local Visible = Query == '' or string.find(ValueText, Query, 1, true) ~= nil;\n                Table.Button.Visible = Visible;\n                if Visible then\n                    VisibleCount = VisibleCount + 1;\n                end\n            end\n\n            local ContentHeight = (VisibleCount * 20) + 8;\n            Scrolling.CanvasPosition = Vector2.new(0, 0);\n            Scrolling.CanvasSize = UDim2.fromOffset(0, ContentHeight);\n            RecalculateListSize(math.max(20, math.min(VisibleCount, MAX_DROPDOWN_ITEMS) * 20 + 1));\n            task.defer(UpdateDropdownScrollVisuals);\n        end;\n\n        SearchBox:GetPropertyChangedSignal('Text'):Connect(ApplyDropdownSearch);\n\n"""
library = replace_once(library, "        local DropdownScrollConnection;\n\n        local function StopDropdownAutoScroll()", "        local DropdownScrollConnection;\n\n" + search_logic + "        local function StopDropdownAutoScroll()", 'search filtering')

library = replace_once(library, """            CancelDropdownTweens();\n            RecalculateListPosition();\n            RecalculateListSize(ListHeight);""", """            CancelDropdownTweens();\n            if SearchBox.Text ~= '' then\n                SearchBox.Text = '';\n            end\n            RecalculateListPosition();\n            RecalculateListSize(ListRowsHeight);\n            ApplyDropdownSearch();""", 'open search reset')

required = [
    "function Dropdown:SetValue(NewValue)",
    "PlaceholderText = 'Search...'",
    "local MinThumbHeight = math.min(18, TrackHeight)",
    "if Visible == DependencyVisible and Holder.Visible == Visible then",
    "Library.ActiveTooltipHide(true)",
    "Text = tostring(Info.Default)",
    "VisibleAnchor = Vector2.new(0.08, 0.832)",
]
for token in required:
    if token not in (library + theme):
        raise SystemExit('missing token: ' + token)
if "DisplayLabel.Text = '<...>'" in library or "DisplayLabel.Text = '<' .. tostring(Key) .. '>'" in library:
    raise SystemExit('angle brackets survived')
if "local ColorFrame = Library:Create('Frame'" in library:
    raise SystemExit('keybind accent strip survived')

library_path.write_text(library)
theme_path.write_text(theme)
