from pathlib import Path

path = Path('addons/ThemeManager.lua')
text = path.read_text()

old_assets = """\tThemeManager.OverlayOrder = { 'EDP445', 'Jane Doe', 'Ibuki' }\n\tThemeManager.OverlayVisualInset = Vector2.new(10, 2)\n\tThemeManager.OverlayAssets = {\n\t\t['EDP445'] = {\n\t\t\tFile = 'edp445.png';\n\t\t\tSize = UDim2.fromOffset(300, 303);\n\t\t\tCanvasSize = Vector2.new(280, 283);\n\t\t\tVisibleEdge = Vector2.new(20, 162);\n\t\t};\n\t\t['Jane Doe'] = {\n\t\t\tFile = 'janedoe.png';\n\t\t\tSize = UDim2.fromOffset(300, 300);\n\t\t\tCanvasSize = Vector2.new(280, 280);\n\t\t\tVisibleEdge = Vector2.new(22, 192);\n\t\t};\n\t\t['Ibuki'] = {\n\t\t\tFile = 'ibuki.png';\n\t\t\tSize = UDim2.fromOffset(300, 300);\n\t\t\tCanvasSize = Vector2.new(280, 280);\n\t\t\tVisibleEdge = Vector2.new(3, 193);\n\t\t};\n\t}\n\tThemeManager.OverlayEnabled = false\n\tThemeManager.OverlaySelection = 'Jane Doe'\n\tThemeManager.OverlayImage = nil\n\tThemeManager.OverlayTween = nil\n\tThemeManager.OverlayAnimationId = 0\n"""
new_assets = """\tThemeManager.OverlayOrder = { 'EDP445', 'Jane Doe', 'Ibuki' }\n\tThemeManager.OverlayVisualInset = Vector2.new(10, 2)\n\tThemeManager.OverlayAssets = {\n\t\t['EDP445'] = {\n\t\t\tFile = 'edp445.png';\n\t\t\tSize = UDim2.fromOffset(300, 303);\n\t\t\tVisibleAnchor = Vector2.new(20 / 280, 162 / 283);\n\t\t};\n\t\t['Jane Doe'] = {\n\t\t\tFile = 'janedoe.png';\n\t\t\tSize = UDim2.fromOffset(300, 300);\n\t\t\tVisibleAnchor = Vector2.new(22 / 280, 192 / 280);\n\t\t};\n\t\t['Ibuki'] = {\n\t\t\tFile = 'ibuki.png';\n\t\t\tSize = UDim2.fromOffset(300, 300);\n\t\t\tVisibleAnchor = Vector2.new(3 / 280, 193 / 280);\n\t\t};\n\t}\n\tThemeManager.OverlayEnabled = false\n\tThemeManager.OverlaySelection = 'Jane Doe'\n\tThemeManager.OverlayImage = nil\n\tThemeManager.OverlayTween = nil\n\tThemeManager.OverlayAnimationId = 0\n\tThemeManager.OverlaySessionId = httpService:GenerateGUID(false)\n\tThemeManager.OverlayAssetCache = {}\n\tThemeManager.OverlayCachePrepared = false\n"""
assert text.count(old_assets) == 1, 'asset metadata block mismatch'
text = text.replace(old_assets, new_assets, 1)

start = text.index("\tfunction ThemeManager:GetOverlayAsset(name)\n")
end = text.index("\n\tfunction ThemeManager:EnsureOverlay()", start)
new_loader = '''\tfunction ThemeManager:PrepareOverlayCache()\n\t\tif self.OverlayCachePrepared then\n\t\t\treturn\n\t\tend\n\n\t\tself.OverlayCachePrepared = true\n\n\t\tif not listfiles or not delfile then\n\t\t\treturn\n\t\tend\n\n\t\tlocal ok, files = pcall(listfiles, 'FormaAssets/idfk')\n\t\tif not ok or type(files) ~= 'table' then\n\t\t\treturn\n\t\tend\n\n\t\tfor _, file in next, files do\n\t\t\tif type(file) == 'string' and file:find('forma-overlay-', 1, true) then\n\t\t\t\tpcall(delfile, file)\n\t\t\tend\n\t\tend\n\tend\n\n\tfunction ThemeManager:IsValidOverlayPng(data)\n\t\treturn type(data) == 'string'\n\t\t\tand #data >= 24\n\t\t\tand data:sub(1, 8) == '\\137PNG\\r\\n\\26\\n'\n\t\t\tand data:sub(13, 16) == 'IHDR'\n\tend\n\n\tfunction ThemeManager:GetPngSize(data)\n\t\tif not self:IsValidOverlayPng(data) then\n\t\t\treturn nil\n\t\tend\n\n\t\tlocal function ReadUInt32BE(index)\n\t\t\tlocal a, b, c, d = string.byte(data, index, index + 3)\n\t\t\tif not a or not b or not c or not d then\n\t\t\t\treturn nil\n\t\t\tend\n\t\t\treturn ((a * 256 + b) * 256 + c) * 256 + d\n\t\tend\n\n\t\tlocal width = ReadUInt32BE(17)\n\t\tlocal height = ReadUInt32BE(21)\n\t\tif not width or not height or width <= 0 or height <= 0 then\n\t\t\treturn nil\n\t\tend\n\n\t\treturn Vector2.new(width, height)\n\tend\n\n\tfunction ThemeManager:GetOverlayAsset(name)\n\t\tlocal info = self.OverlayAssets[name]\n\t\tlocal getCustomAsset = getcustomasset or getsynasset\n\n\t\tif not info or not getCustomAsset or not writefile then\n\t\t\treturn nil\n\t\tend\n\n\t\tif self.OverlayAssetCache[name] then\n\t\t\treturn self.OverlayAssetCache[name]\n\t\tend\n\n\t\tif makefolder then\n\t\t\tif not isfolder or not isfolder('FormaAssets') then\n\t\t\t\tpcall(makefolder, 'FormaAssets')\n\t\t\tend\n\n\t\t\tif not isfolder or not isfolder('FormaAssets/idfk') then\n\t\t\t\tpcall(makefolder, 'FormaAssets/idfk')\n\t\t\tend\n\t\tend\n\n\t\tself:PrepareOverlayCache()\n\n\t\tlocal url = self.OverlayBaseUrl .. info.File .. '?v=' .. self.OverlaySessionId\n\t\tlocal ok, data = pcall(function()\n\t\t\treturn game:HttpGet(url)\n\t\tend)\n\n\t\tif not ok or not self:IsValidOverlayPng(data) then\n\t\t\treturn nil\n\t\tend\n\n\t\tinfo.SourceSize = self:GetPngSize(data)\n\n\t\tlocal safeFile = info.File:gsub('[^%w%._%-]', '_')\n\t\tlocal localPath = 'FormaAssets/idfk/forma-overlay-' .. self.OverlaySessionId .. '-' .. safeFile\n\t\tlocal wrote = pcall(writefile, localPath, data)\n\t\tif not wrote then\n\t\t\treturn nil\n\t\tend\n\n\t\tlocal assetOk, asset = pcall(getCustomAsset, localPath)\n\t\tif not assetOk or not asset then\n\t\t\treturn nil\n\t\tend\n\n\t\tself.OverlayAssetCache[name] = asset\n\t\treturn asset\n\tend\n'''
text = text[:start] + new_loader + text[end:]

old_position = """\tfunction ThemeManager:GetOverlayPosition(info)\n\t\tlocal scaleX = info.Size.X.Offset / info.CanvasSize.X\n\t\tlocal scaleY = info.Size.Y.Offset / info.CanvasSize.Y\n\n\t\treturn UDim2.fromOffset(\n\t\t\tself.OverlayVisualInset.X - (info.VisibleEdge.X * scaleX),\n\t\t\tself.OverlayVisualInset.Y - (info.VisibleEdge.Y * scaleY)\n\t\t)\n\tend\n"""
new_position = """\tfunction ThemeManager:GetOverlayPosition(info)\n\t\treturn UDim2.fromOffset(\n\t\t\tself.OverlayVisualInset.X - (info.Size.X.Offset * info.VisibleAnchor.X),\n\t\t\tself.OverlayVisualInset.Y - (info.Size.Y.Offset * info.VisibleAnchor.Y)\n\t\t)\n\tend\n"""
assert text.count(old_position) == 1, 'position helper mismatch'
text = text.replace(old_position, new_position, 1)

needle = """\t\t\tself.OverlayImage = self.Library:Create('ImageLabel', {\n\t\t\t\tName = 'FormaThemeOverlay';\n\t\t\t\tActive = false;\n\t\t\t\tAnchorPoint = Vector2.new(0, 0);\n\t\t\t\tBackgroundTransparency = 1;\n\t\t\t\tBorderSizePixel = 0;\n\t\t\t\tImage = '';\n\t\t\t\tImageTransparency = 1;\n\t\t\t\tScaleType = Enum.ScaleType.Fit;\n\t\t\t\tVisible = false;\n\t\t\t\tZIndex = 500;\n\t\t\t\tParent = holder;\n\t\t\t})\n"""
replacement = needle + """\n\t\t\tpcall(function()\n\t\t\t\tself.OverlayImage.ResampleMode = Enum.ResamplerMode.Default\n\t\t\tend)\n"""
assert text.count(needle) == 1, 'overlay image creation mismatch'
text = text.replace(needle, replacement, 1)

assert 'needsDownload' not in text
assert "data:sub(1, 8) == '\\137PNG\\r\\n\\26\\n'" in text
assert text.count('OverlayAssetCache = {}') == 1
assert text.count('VisibleAnchor = Vector2.new') == 3
assert 'CanvasSize = Vector2.new(280' not in text
assert 'VisibleEdge = Vector2.new' not in text

path.write_text(text)
